# Form implementation generated from reading ui file 'forms\AboutDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(270, 115)
        AboutDialog.setMinimumSize(QtCore.QSize(270, 115))
        AboutDialog.setMaximumSize(QtCore.QSize(270, 115))
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AboutDialog)
        self.buttonBox.setGeometry(QtCore.QRect(10, 80, 251, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.versionLabel = QtWidgets.QLabel(parent=AboutDialog)
        self.versionLabel.setGeometry(QtCore.QRect(10, 10, 231, 16))
        self.versionLabel.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.versionLabel.setOpenExternalLinks(False)
        self.versionLabel.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.versionLabel.setObjectName("versionLabel")
        self.homeLink = QtWidgets.QLabel(parent=AboutDialog)
        self.homeLink.setGeometry(QtCore.QRect(10, 40, 49, 16))
        self.homeLink.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.homeLink.setOpenExternalLinks(True)
        self.homeLink.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.LinksAccessibleByMouse|QtCore.Qt.TextInteractionFlag.TextEditable|QtCore.Qt.TextInteractionFlag.TextEditorInteraction|QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.homeLink.setObjectName("homeLink")
        self.iconsLink = QtWidgets.QLabel(parent=AboutDialog)
        self.iconsLink.setGeometry(QtCore.QRect(10, 60, 171, 16))
        self.iconsLink.setTextFormat(QtCore.Qt.TextFormat.RichText)
        self.iconsLink.setOpenExternalLinks(True)
        self.iconsLink.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextBrowserInteraction)
        self.iconsLink.setObjectName("iconsLink")

        self.retranslateUi(AboutDialog)
        self.buttonBox.accepted.connect(AboutDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About"))
        self.versionLabel.setText(_translate("AboutDialog", "Log Viewer v."))
        self.homeLink.setText(_translate("AboutDialog", "<html><head/><body><p>Home: </p></body></html>"))
        self.iconsLink.setText(_translate("AboutDialog", "<html><head/><body><p>Icons: <a href=\"\\&quot;http://icons8.com/\\&quot;\"><span style=\" text-decoration: underline; color:#0000ff;\">http://icons8.com</span></a></p></body></html>"))
