# Form implementation generated from reading ui file 'forms\ImportDialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(345, 110)
        ImportDialog.setMinimumSize(QtCore.QSize(345, 110))
        ImportDialog.setMaximumSize(QtCore.QSize(345, 110))
        self.label = QtWidgets.QLabel(parent=ImportDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 301, 21))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=ImportDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 40, 121, 21))
        self.label_2.setObjectName("label_2")
        self.messageCount = QtWidgets.QLabel(parent=ImportDialog)
        self.messageCount.setGeometry(QtCore.QRect(148, 40, 171, 21))
        self.messageCount.setObjectName("messageCount")
        self.cancelButton = QtWidgets.QPushButton(parent=ImportDialog)
        self.cancelButton.setGeometry(QtCore.QRect(110, 70, 121, 31))
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(ImportDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)

    def retranslateUi(self, ImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDialog.setWindowTitle(_translate("ImportDialog", "Import Progress"))
        self.label.setText(_translate("ImportDialog", "Importing log-file in progress..."))
        self.label_2.setText(_translate("ImportDialog", "Messages processed:"))
        self.messageCount.setText(_translate("ImportDialog", "0"))
        self.cancelButton.setText(_translate("ImportDialog", "Cancel"))
